"""create outlay

Revision ID: a125f8916d2a
Revises: 82762a10d389
Create Date: 2025-04-08 08:53:51.299814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a125f8916d2a'
down_revision: Union[str, None] = '82762a10d389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlay_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Приоритет(0-обязательно, 1-комфорт, 2-вредно)'),
    sa.Column('title', sa.String(length=20), nullable=False, comment='Заголовок'),
    sa.Column('description', sa.String(length=20), nullable=True, comment='Описание'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Категории расходов'
    )
    op.create_table('outlays',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('outlay_category_id', sa.Integer(), nullable=False, comment='ID категории расхода'),
    sa.Column('value', sa.Float(), nullable=False, comment='Значение'),
    sa.Column('comment', sa.String(length=100), nullable=True, comment='Комментарий'),
    sa.Column('outlay_date', sa.Date, nullable=False, comment='Дата расхода'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['outlay_category_id'], ['outlay_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Расходы'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlays')
    op.drop_table('outlay_categories')
    # ### end Alembic commands ###
