"""create income

Revision ID: 82762a10d389
Revises: aa3b012601ba
Create Date: 2025-04-08 08:44:59.086244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82762a10d389'
down_revision: Union[str, None] = 'aa3b012601ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False, comment='Заголовок'),
    sa.Column('description', sa.String(length=20), nullable=True, comment='Описание'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Категории доходов'
    )
    op.create_table('incomes',
    sa.Column('income_category_id', sa.Integer(), nullable=False, comment='ID категории дохода'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('value', sa.Float(), nullable=False, comment='Значение'),
    sa.Column('income_date', sa.Date, nullable=False, comment='Дата дохода'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['income_category_id'], ['income_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Доходы'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incomes')
    op.drop_table('income_categories')
    # ### end Alembic commands ###
