"""create user

Revision ID: aa3b012601ba
Revises: 
Create Date: 2025-04-08 08:44:34.970356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3b012601ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=20), nullable=False, comment='Имя'),
    sa.Column('second_name', sa.String(length=20), nullable=False, comment='Фамилия'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата добавления'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='email'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Хэш пароля'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='Пользователи'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
